feat: makes nerdctl available to pull nydus images
containerd/nerdctl pull request #1163
Opened 2022-06-24 11:00 UTC by loheagn

This patch will enable the users to pull/run nydus images using nerdctl.

For example, users can pull nydus images:

```
nerdctl --snapshotter nydus pull <image_name>
```

or run nydus images:

```
nerdctl --snapshotter nydus run <image_name>
```

This patch appends image's basic informations to each layer descriptor as annotations during unpack. These annotations will be passed to this nydus snapshotter as labels.

2022-06-25 04:28 UTC, manugupt1 approved these changes

2022-06-25 09:29 UTC, junnplus commented
> Signed-off-by: loheagn

Please use your real name

2022-06-25 09:31 UTC, junnplus requested changes
We needs some tests for make sure it works.

2022-06-25 10:53 UTC, fahedouch commented on pkg/imgutil/imgutil.go
> +		nydus = isNydus(snapshotter)
I think it is better to refacto this list of snapshotter into switch statement but this can be done in another PR

2022-06-28 00:30 UTC, AkihiroSuda commented on go.sum
> +github.com/docker/docker v1.6.1/go.mod h1:eEKB0N0r5NX/I1kEveEz05bcu8tLC/8azJZsviup8Sk=
What is this?

2022-06-28 00:30 UTC, AkihiroSuda commented on go.sum
> +github.com/docker/libcontainer v2.2.1+incompatible/go.mod h1:osvj61pYsqhNCMLGX31xr7klUBhHb/ZBuXS0o1Fvwbw=
What is this?
Very old package.

2022-06-28 00:31 UTC, AkihiroSuda commented on pkg/imgutil/imgutil.go
> +	"github.com/containerd/nydus-snapshotter/pkg/label"
```suggestion
	nyduslabel "github.com/containerd/nydus-snapshotter/pkg/label"
```

2022-06-28 16:25 UTC, loheagn commented
> Thanks, the code looks good but wondering if we could wipe out ancient packages such as docker/libcontainer and docker/docker@v1.6.1 from `go.sum`

Thanks for the review. I'll fix it.

2022-07-01 07:45 UTC, loheagn commented
> We needs some tests for make sure it works.

Hi, @junnplus , sorry for the late reply. But I find it's hard to add a unit test for this function. I think the function is pretty simple and shouldn't go wrong. We can add an e2e test in containerd/nydus-snapshotter after this PR to make sure nerdctl works well with nydus-snapshotter.

2022-07-01 08:49 UTC, AkihiroSuda commented
Please squash commits

2022-07-01 12:16 UTC, loheagn commented
> Please squash commits

Done :)

2022-07-01 18:14 UTC, hsiangkao approved these changes

2022-07-02 04:41 UTC, junnplus approved these changes
LGTM

2022-07-02 06:16 UTC, AkihiroSuda approved these changes

2022-07-02 06:17 UTC, merged