Binary log provider to extend logging
containerd/nerdctl pull request #1354
Opened 2022-09-04 22:47 UTC by manugupt1

Implements third provider logging

https://github.com/containerd/nerdctl/issues/1039

This is a WIP. Opening it for review

2022-09-04 23:09 UTC, AkihiroSuda requested changes
Thanks, but I think the right way is to use `cio.BinaryIO`: https://pkg.go.dev/github.com/containerd/containerd@v1.6.8/cio#BinaryIO

We can also consider just supporting https://pkg.go.dev/github.com/containerd/containerd@v1.6.8/cio#LogURIGenerator in `--log-driver` (`nerdctl run --log-driver binary://foo?bar=baz`)

2022-09-05 22:53 UTC, manugupt1 commented
@AkihiroSuda Does this sound reasonable? I tested locally, I wanted to check-in with you. Any suggestions on writing an integ-test?

2022-09-07 02:26 UTC, AkihiroSuda commented
Thanks

> Any suggestions on writing an integ-test?

What about implementing a test binary in a small shell script under `t.Tempdir()`, and set `$PATH` to there?

2022-09-07 02:26 UTC, AkihiroSuda commented on README.md
> +    - :nerd_face: Accepts a LogURI which is a containerd shim logger. A scheme must be specified for the URI.
Needs example URIs

2022-09-07 05:55 UTC, Zheaoli commented
https://github.com/containerd/nerdctl/pull/1256/files#diff-7312cd37020aca19ab86ba2f16dc89e6cf1a5a0580eb6ec3dc2aa06b3cd1ccb9L147

@manugupt1 @AkihiroSuda This piece of code may help to impl the e2e test

2022-09-11 04:29 UTC, manugupt1 commented
> Thanks
> 
> > Any suggestions on writing an integ-test?
> 
> What about implementing a test binary in a small shell script under `t.Tempdir()`, and set `$PATH` to there?

Tried writing a bash file; but could not; not sure why. Here is the gist: https://gist.github.com/manugupt1/19db623c5cb3cc11a2cb58f23a176ba5

That's why I went with @Zheaoli's suggestion.

2022-09-11 06:18 UTC, AkihiroSuda commented on README.md
> +    - :nerd_face: Accepts a LogURI which is a containerd shim logger. A scheme must be specified for the URI. Example: `nerdctl run -d --log-driver binary:/usr/bin/ctr-journald-shim docker.io/library
Probably
```suggestion
    - :nerd_face: Accepts a LogURI which is a containerd shim logger. A scheme must be specified for the URI. Example: `nerdctl run -d --log-driver binary:///usr/bin/ctr-journald-shim docker.io/library/hello-world:latest`. An implementation of shim logger can be found at (https://github.com/containerd/containerd/tree/dbef1d56d7ebc05bc4553d72c419ed5ce025b05d/runtime/v2#logging)
```

2022-09-11 06:18 UTC, AkihiroSuda commented on cmd/nerdctl/run_test.go
> +		t.Skip("journald log driver is not yet implemented on Windows")
Doesn't seem relevant to journald

2022-09-11 06:19 UTC, AkihiroSuda commented on cmd/nerdctl/run_test.go
> +	base.Cmd("cp", fmt.Sprintf("%s:/go/src/logger/logger", containerName), tmpDir).AssertOK()
You can use `nerdctl build --output` to simplify these commands

2022-09-11 06:19 UTC, AkihiroSuda commented on cmd/nerdctl/run_test.go
> +	var wg sync.WaitGroup \n\
indent

2022-09-11 10:54 UTC, AkihiroSuda approved these changes
Thanks

2022-09-11 10:54 UTC, merged