Support build args without explicit value
containerd/nerdctl pull request #1417
Opened 2022-10-06 13:41 UTC by alebcay

This PR fixes https://github.com/containerd/nerdctl/issues/1408.

When a build arg key is specified without an explicit value, [the value should be taken from the corresponding environment variable on the host](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg).

When the corresponding environment variable on the host is unset, [the build arg should be ignored](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file) to [avoid masking a possible default value specified in the Dockerfile](https://github.com/moby/moby/issues/24101). To pass an empty string as build arg, use the form `VAR=` on the CLI/as an environment variable.

2022-10-06 14:43 UTC, Zheaoli requested changes

2022-10-06 14:43 UTC, Zheaoli commented on cmd/nerdctl/build_test.go
> +	err = os.Unsetenv("TEST_STRING")
nits: maybe using defer statement here is a good choice

2022-10-19 02:50 UTC, ktock approved these changes

2022-10-19 02:59 UTC, AkihiroSuda approved these changes
Thanks

2022-10-19 02:59 UTC, merged