Make titles Bold in `nerdctl` output
containerd/nerdctl pull request #1643
Opened 2022-12-12 17:58 UTC by aman556

## Description
This PR is making the titles bold in the output of `nerdctl` command.

## Testing
- Build the project and run `nerdctl` command

## Output
Image in the first comment

Signed-off-by: Aman Sharma <amansh@vmware.com>

2022-12-12 18:00 UTC, aman556 commented
<img width="1104" alt="Screenshot 2022-12-12 at 11 27 10 PM" src="https://user-images.githubusercontent.com/56108587/207119352-0d6ee829-145a-41aa-951f-defde32f3f66.png">
Notice that the Management commands:, Commands:, and Flags: are bold.

2022-12-12 18:13 UTC, Zheaoli commented
Would you mind adding an image in the old version to let us know the effect detail?

2022-12-12 18:27 UTC, aman556 commented
@Zheaoli old version output image
<img width="1058" alt="Screenshot 2022-12-12 at 11 55 35 PM" src="https://user-images.githubusercontent.com/56108587/207124904-55133f48-d8d4-4c2d-83ed-5c83aa639270.png">

2022-12-12 18:59 UTC, Zheaoli requested changes
LGTM for code

need squash the commit

2022-12-13 12:06 UTC, AkihiroSuda commented
Thanks, but let me merge https://github.com/containerd/nerdctl/pull/1639 first

2022-12-13 12:22 UTC, fahedouch commented on cmd/nerdctl/main.go
> +	Bold = color.New(color.Bold).SprintfFunc()
unexported var is fine :  `bold`

2022-12-16 18:03 UTC, merged