FIX: `options.Stdout` should be used instead of `os.Stdout`
containerd/nerdctl pull request #2032
Opened 2023-02-20 04:42 UTC by rkonfj

In package `pkg/cmd/container`, `List` function which print containers to `options.Stdout` should always print to `options.Stdout`

2023-02-20 06:28 UTC, suyanhanx commented
Please append your DCO sign to the PR description.

2023-02-20 16:25 UTC, fahedouch requested changes

2023-02-20 16:25 UTC, fahedouch commented on pkg/cmd/container/list.go
> +		w = tabwriter.NewWriter(options.Stdout, 4, 8, 4, ' ', 0)
could you please use the `w` var : `w = tabwriter.NewWriter(w, 4, 8, 4, ' ', 0)`

2023-02-20 16:25 UTC, fahedouch commented on pkg/cmd/container/list.go
> +		w = tabwriter.NewWriter(options.Stdout, 4, 8, 4, ' ', 0)
could you please use the `w` var : `w = tabwriter.NewWriter(w, 4, 8, 4, ' ', 0)`

2023-02-21 04:36 UTC, AkihiroSuda approved these changes
Thanks

2023-02-21 04:36 UTC, merged