update runc (1.2.0-rc.2)
containerd/nerdctl pull request #3153
Opened 2024-06-27 13:34 UTC by AkihiroSuda

2024-06-27 13:41 UTC, AkihiroSuda commented
```
 > [linux/amd64->arm64 build-runc 4/4] RUN GO=xx-go make static &&   xx-verify --static runc && cp -v -a runc /out/runc.arm64:
0.548 rm -f libcontainer/dmz/binary/runc-dmz
0.558 xx-go generate -tags "seccomp urfave_cli_no_docs " ./libcontainer/dmz
1.260 make[1]: Entering directory '/go/src/github.com/opencontainers/runc/libcontainer/dmz'
1.346 aarch64-linux-gnu-gcc -fno-asynchronous-unwind-tables -fno-ident -s -Os -nostdlib -lgcc -static -o binary/runc-dmz _dmz.c
1.745 strip -gs binary/runc-dmz
1.748 strip: Unable to recognise the format of the input file `binary/runc-dmz'
1.755 make[1]: Leaving directory '/go/src/github.com/opencontainers/runc/libcontainer/dmz'
1.755 make[1]: *** [Makefile:19: binary/runc-dmz] Error 1
1.755 libcontainer/dmz/dmz_linux.go:27: running "make": exit status 2
1.759 make: *** [Makefile:110: runc-dmz] Error 1
```
https://github.com/containerd/nerdctl/actions/runs/9697606568/job/26762120686?pr=3153

2024-06-28 02:34 UTC, AkihiroSuda commented
```
SKIP github.com/containerd/nerdctl/v2/cmd/nerdctl.TestComposePushAndPullWithCosignVerify (0.02s)
PASS github.com/containerd/nerdctl/v2/cmd/nerdctl.TestComposeStart (2.26s)
SKIP github.com/containerd/nerdctl/v2/cmd/nerdctl.TestComposeStartFailWhenServicePause (0.03s)
PASS github.com/containerd/nerdctl/v2/cmd/nerdctl.TestComposeStop (12.25s)
SKIP github.com/containerd/nerdctl/v2/cmd/nerdctl.TestComposeTop (0.00s)
PASS github.com/containerd/nerdctl/v2/cmd/nerdctl.TestComposeUp (7.56s)
SKIP github.com/containerd/nerdctl/v2/cmd/nerdctl.TestComposeUpBuild (0.02s)
SKIP github.com/containerd/nerdctl/v2/cmd/nerdctl.TestComposeUpNetWithStaticIP (0.00s)
PASS github.com/containerd/nerdctl/v2/cmd/nerdctl.TestComposeUpMultiNet (1.78s)
PASS github.com/containerd/nerdctl/v2/cmd/nerdctl.TestComposeUpOsEnvVar (0.49s)
PASS github.com/containerd/nerdctl/v2/cmd/nerdctl.TestComposeUpDotEnvFile (0.48s)
PASS github.com/containerd/nerdctl/v2/cmd/nerdctl.TestComposeUpEnvFileNotFoundError (0.07s)
PASS github.com/containerd/nerdctl/v2/cmd/nerdctl.TestComposeUpWithScale (0.51s)
PASS github.com/containerd/nerdctl/v2/cmd/nerdctl.TestComposeIPAMConfig (0.45s)
PASS github.com/containerd/nerdctl/v2/cmd/nerdctl.TestComposeUpRemoveOrphans (1.35s)
PASS github.com/containerd/nerdctl/v2/cmd/nerdctl.TestComposeUpIdempotent (0.78s)
PASS github.com/containerd/nerdctl/v2/cmd/nerdctl.TestComposeUpWithExternalNetwork (1.27s)
systemd [245](https://github.com/containerd/nerdctl/actions/runs/9697606582/job/26762124957?pr=3153#step:6:246).4-4ubuntu3.23 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid)
Detected virtualization docker.
Detected architecture x86-64.
Error: Timeout of 1800000ms hit
```


https://github.com/containerd/nerdctl/actions/runs/9697606582/job/26762124957?pr=3153

2024-08-17 20:34 UTC, apostasie commented
Wish we had runc rc3.

https://github.com/opencontainers/runc/issues/4114#issuecomment-2276341600

2024-08-23 21:20 UTC, apostasie commented
LGTM.
The failure was likely unrelated (TestAttach is flaky) and the retry timed-out.

I think we should have this ASAP to get more soak-time on the CI before 2.0.

2024-09-03 02:57 UTC, apostasie approved these changes

2024-09-03 03:57 UTC, AkihiroSuda commented
`test / test-integration-rootless (20.04, v1.6.33, v1.1.1, test-integration-rootless)` can't be green
https://github.com/containerd/nerdctl/actions/runs/10675191963/job/29588507388?pr=3153

<details>

<p>

```
test target: "nerdctl"
PASS cmd/nerdctl.TestIssue108 (1.84s)
PASS cmd/nerdctl.TestNerdctlConfigBad (0.01s)
PASS cmd/nerdctl.TestNerdctlConfig (0.14s)
PASS cmd/nerdctl.TestUnknownCommand (0.16s)
PASS cmd/nerdctl
test target: "nerdctl"
EMPTY cmd/nerdctl/apparmor
test target: "nerdctl"
SKIP cmd/nerdctl/builder.TestBuildContextWithOCILayout (0.02s)
SKIP cmd/nerdctl/builder.TestBuild (0.02s)
SKIP cmd/nerdctl/builder.TestBuildIsShareableForCompatiblePlatform (0.02s)
SKIP cmd/nerdctl/builder.TestBuildBaseImage (0.02s)
SKIP cmd/nerdctl/builder.TestBuildFromContainerd (0.02s)
SKIP cmd/nerdctl/builder.TestBuildFromStdin (0.02s)
SKIP cmd/nerdctl/builder.TestBuildWithDockerfile (0.02s)
SKIP cmd/nerdctl/builder.TestBuildLocal (0.02s)
SKIP cmd/nerdctl/builder.TestBuildWithBuildArg (0.02s)
SKIP cmd/nerdctl/builder.TestBuildWithIIDFile (0.02s)
SKIP cmd/nerdctl/builder.TestBuildWithLabels (0.02s)
SKIP cmd/nerdctl/builder.TestBuildMultipleTags (0.02s)
SKIP cmd/nerdctl/builder.TestBuildWithContainerfile (0.02s)
SKIP cmd/nerdctl/builder.TestBuildWithDockerFileAndContainerfile (0.02s)
SKIP cmd/nerdctl/builder.TestBuildNoTag (0.02s)
SKIP cmd/nerdctl/builder.TestBuildContextDockerImageAlias (0.02s)
SKIP cmd/nerdctl/builder.TestBuildContextWithCopyFromDir (0.02s)
SKIP cmd/nerdctl/builder.TestBuildSourceDateEpoch (0.02s)
SKIP cmd/nerdctl/builder.TestBuildNetwork (0.02s)
PASS cmd/nerdctl/builder.TestBuildNetworkShellCompletion (0.02s)
SKIP cmd/nerdctl/builder.TestBuildAttestation (0.02s)
SKIP cmd/nerdctl/builder.TestBuilderPrune (0.02s)
PASS cmd/nerdctl/builder.TestBuilderDebug (0.54s)
SKIP cmd/nerdctl/builder.TestBuildWithPull (0.00s)
PASS cmd/nerdctl/builder
test target: "nerdctl"
PASS cmd/nerdctl/completion.TestCompletion (0.73s)
PASS cmd/nerdctl/completion
test target: "nerdctl"
SKIP cmd/nerdctl/compose.TestComposeBuild (0.02s)
PASS cmd/nerdctl/compose.TestComposeConfig (0.02s)
PASS cmd/nerdctl/compose.TestComposeConfigWithPrintService (0.02s)
PASS cmd/nerdctl/compose.TestComposeConfigWithPrintServiceHash (0.07s)
PASS cmd/nerdctl/compose.TestComposeConfigWithMultipleFile (0.07s)
PASS cmd/nerdctl/compose.TestComposeConfigWithComposeFileEnv (0.07s)
PASS cmd/nerdctl/compose.TestComposeConfigWithEnvFile (0.02s)
PASS cmd/nerdctl/compose.TestComposeCopy (10.56s)
PASS cmd/nerdctl/compose.TestComposeCreate (0.47s)
PASS cmd/nerdctl/compose.TestComposeCreateDependency (0.28s)
PASS cmd/nerdctl/compose.TestComposeCreatePull (1.61s)
SKIP cmd/nerdctl/compose.TestComposeCreateBuild (0.02s)
PASS cmd/nerdctl/compose.TestComposeDownRemoveUsedNetwork (20.81s)
PASS cmd/nerdctl/compose.TestComposeDownRemoveOrphans (10.75s)
PASS cmd/nerdctl/compose.TestComposeExec (10.62s)
PASS cmd/nerdctl/compose.TestComposeExecWithEnv (10.52s)
PASS cmd/nerdctl/compose.TestComposeExecWithUser (10.92s)
PASS cmd/nerdctl/compose.TestComposeExecTTY (10.86s)
PASS cmd/nerdctl/compose.TestComposeExecWithIndex (13.13s)
PASS cmd/nerdctl/compose.TestComposeImages (54.91s)
PASS cmd/nerdctl/compose.TestComposeImagesJson (12.19s)
PASS cmd/nerdctl/compose.TestComposeKill (5.19s)
SKIP cmd/nerdctl/compose.TestComposePauseAndUnpause (0.02s)
PASS cmd/nerdctl/compose.TestComposePort (10.57s)
PASS cmd/nerdctl/compose.TestComposePortFailure (10.60s)
PASS cmd/nerdctl/compose.TestComposePs (5.74s)
PASS cmd/nerdctl/compose.TestComposePsJSON (11.53s)
PASS cmd/nerdctl/compose.TestComposePullWithService (0.24s)
PASS cmd/nerdctl/compose.TestComposeRestart (24.42s)
PASS cmd/nerdctl/compose.TestComposeRemove (11.47s)
PASS cmd/nerdctl/compose.TestComposeRun (0.42s)
PASS cmd/nerdctl/compose.TestComposeRunWithRM (0.44s)
PASS cmd/nerdctl/compose.TestComposeRunWithServicePorts (4.27s)
PASS cmd/nerdctl/compose.TestComposeRunWithPublish (0.58s)
PASS cmd/nerdctl/compose.TestComposeRunWithEnv (0.42s)
PASS cmd/nerdctl/compose.TestComposeRunWithUser (0.42s)
PASS cmd/nerdctl/compose.TestComposeRunWithLabel (0.47s)
PASS cmd/nerdctl/compose.TestComposeRunWithArgs (0.42s)
PASS cmd/nerdctl/compose.TestComposeRunWithEntrypoint (0.42s)
PASS cmd/nerdctl/compose.TestComposeRunWithVolume (0.44s)
SKIP cmd/nerdctl/compose.TestComposePushAndPullWithCosignVerify (0.02s)
PASS cmd/nerdctl/compose.TestComposeStart (22.34s)
SKIP cmd/nerdctl/compose.TestComposeStartFailWhenServicePause (0.02s)
PASS cmd/nerdctl/compose.TestComposeStop (12.23s)
SKIP cmd/nerdctl/compose.TestComposeTop (0.00s)
PASS cmd/nerdctl/compose.TestComposeUp (14.07s)
SKIP cmd/nerdctl/compose.TestComposeUpBuild (0.02s)
SKIP cmd/nerdctl/compose.TestComposeUpNetWithStaticIP (0.00s)
PASS cmd/nerdctl/compose.TestComposeUpMultiNet (2.07s)
PASS cmd/nerdctl/compose.TestComposeUpOsEnvVar (0.59s)
PASS cmd/nerdctl/compose.TestComposeUpDotEnvFile (0.50s)
PASS cmd/nerdctl/compose.TestComposeUpEnvFileNotFoundError (0.04s)
PASS cmd/nerdctl/compose.TestComposeUpWithScale (10.59s)
PASS cmd/nerdctl/compose.TestComposeIPAMConfig (10.45s)
PASS cmd/nerdctl/compose.TestComposeUpRemoveOrphans (11.36s)
PASS cmd/nerdctl/compose.TestComposeUpIdempotent (10.78s)
PASS cmd/nerdctl/compose.TestComposeUpWithExternalNetwork (1.33s)
PASS cmd/nerdctl/compose.TestComposeUpWithBypass4netns (14.22s)
PASS cmd/nerdctl/compose.TestComposeUpProfile (1.37s)
PASS cmd/nerdctl/compose.TestComposeUpAbortOnContainerExit (8.43s)
PASS cmd/nerdctl/compose.TestComposeUpDetailedError (0.10s)
PASS cmd/nerdctl/compose.TestComposeUpBindCreateHostPath (0.45s)
PASS cmd/nerdctl/compose.TestComposeVersion (0.02s)
PASS cmd/nerdctl/compose.TestComposeVersionShort (0.02s)
PASS cmd/nerdctl/compose.TestComposeVersionJson (0.02s)
PASS cmd/nerdctl/compose
test target: "nerdctl"
PASS cmd/nerdctl/container.TestCreateWithMACAddress/nerdctl-testcreatewithmacaddress_container:nerdctl-testcreatewithmacaddress_2_network:container:whatevernerdctl-testcreatewithmacaddress_expect:container (0.29s)
PASS cmd/nerdctl/container.TestCreateWithMACAddress/nerdctl-testcreatewithmacaddress_container:nerdctl-testcreatewithmacaddress_1_network:none_expect: (0.35s)
PASS cmd/nerdctl/container.TestCreateWithMACAddress/nerdctl-testcreatewithmacaddress_container:nerdctl-testcreatewithmacaddress_6_network:testNetworkIPvlannerdctl-testcreatewithmacaddress_expect:not_support (0.13s)
PASS cmd/nerdctl/container.TestCreateWithMACAddress/nerdctl-testcreatewithmacaddress_container:nerdctl-testcreatewithmacaddress_0_network:host_expect: (0.45s)
PASS cmd/nerdctl/container.TestCreateWithMACAddress/nerdctl-testcreatewithmacaddress_container:nerdctl-testcreatewithmacaddress_4_network:testNetworkBridgenerdctl-testcreatewithmacaddress_expect:we_expect_the_generated_mac_on_the_output (0.66s)
PASS cmd/nerdctl/container.TestCreateWithMACAddress/nerdctl-testcreatewithmacaddress_container:nerdctl-testcreatewithmacaddress_5_network:testNetworkMACvlannerdctl-testcreatewithmacaddress_expect:we_expect_the_generated_mac_on_the_output (0.44s)
PASS cmd/nerdctl/container.TestCreateWithMACAddress/nerdctl-testcreatewithmacaddress_container:nerdctl-testcreatewithmacaddress_3_network:bridge_expect:we_expect_the_generated_mac_on_the_output (0.43s)
PASS cmd/nerdctl/container.TestCreateWithMACAddress (0.45s)
PASS cmd/nerdctl/container.TestCreateWithTty (0.72s)
PASS cmd/nerdctl/container.TestContainerInspectContainsPortConfig (0.40s)
PASS cmd/nerdctl/container.TestContainerInspectContainsMounts (0.34s)
SKIP cmd/nerdctl/container.TestKillCleanupForwards (0.02s)
PASS cmd/nerdctl/container.TestContainerList (0.82s)
PASS cmd/nerdctl/container.TestContainerListWideMode (0.94s)
PASS cmd/nerdctl/container.TestContainerListWithLabels (0.84s)
PASS cmd/nerdctl/container.TestContainerListWithNames (0.82s)
PASS cmd/nerdctl/container.TestContainerListWithFilter (2.89s)
PASS cmd/nerdctl/container.TestContainerListCheckCreatedTime (3.11s)
PASS cmd/nerdctl/container.TestTailFollowRotateLogs (1.30s)
PASS cmd/nerdctl/container.TestPr [...]

2024-09-03 04:00 UTC, apostasie commented
> `test / test-integration-rootless (20.04, v1.6.33, v1.1.1, test-integration-rootless)` can't be green https://github.com/containerd/nerdctl/actions/runs/10675191963/job/29588507388?pr=3153

Is that related to the runc update?

2024-09-03 05:00 UTC, AkihiroSuda commented
> > `test / test-integration-rootless (20.04, v1.6.33, v1.1.1, test-integration-rootless)` can't be green https://github.com/containerd/nerdctl/actions/runs/10675191963/job/29588507388?pr=3153
> 
> Is that related to the runc update?

Probably yes. runc apparently has a regression for cgroup v1.

2024-09-04 07:42 UTC, AkihiroSuda commented
The failure on local Ubuntu 20.04 (`docker build -t foo --target test-integration-rootless --build-arg UBUNTU_VERSION=20.04 --build-arg CONTAINERD_VERSION=v1.6.33 --build-arg ROOTLESSKIT_VERSION=v1.1.1 . && docker run -t --rm --privileged foo`):
```
=== FAIL: cmd/nerdctl/container  (0.00s)                                                                                                                                                                     
test target: "nerdctl"                                                                                                                                                                                       
panic: test timed out after 1h0m0s                                                                                                                                                                           
        running tests:                                                                                                                                                                                       
                TestCopyFromContainer (53m20s)                                                                                                                                                               
                TestCopyFromContainer/SRC_PATH_specifies_a_file (53m17s)                                                                                                                                     
                TestCopyFromContainer/SRC_PATH_specifies_a_file/SRC_PATH_is_in_a_volume (53m17s)                                                                                                             
                TestLogsWithForegroundContainers (53m19s)                                                                                                                                                    
                TestRestartIPCContainer (53m31s)                                                                                                                                                             
                TestRestartPIDContainer (53m31s)
```

2024-09-04 08:15 UTC, AkihiroSuda commented
`TestRestartPIDContainer` seems the culprit

2024-09-04 15:14 UTC, AkihiroSuda commented
Something is hanging here
https://github.com/containerd/nerdctl/blob/53d898dabdf0c3a2166ef344453b77013df4452a/cmd/nerdctl/container/container_restart_linux_test.go#L60

2024-09-04 17:17 UTC, AkihiroSuda commented
Opened an issue in the runc repo
- https://github.com/opencontainers/runc/issues/4394

2024-10-22 09:18 UTC, AkihiroSuda commented on hack/build-integration-canary.sh
> +blacklist=(none)
This can't be just `()`

```
./hack/build-integration-canary.sh: line 228: bl: unbound variable
```

2024-10-22 09:21 UTC, apostasie commented on hack/build-integration-canary.sh
> +blacklist=(none)
Interesting.
Will have a look

2024-10-22 09:42 UTC, apostasie commented on hack/build-integration-canary.sh
> +blacklist=(none)
Can you do on line 218:
```bash
canary::build::integration(){
  local bl=""
```

2024-10-22 09:43 UTC, apostasie commented on hack/build-integration-canary.sh
> +blacklist=(none)
`blacklist=()` should work then

2024-10-22 09:47 UTC, apostasie requested changes

2024-10-22 09:47 UTC, apostasie commented on hack/build-integration-canary.sh
> +blacklist=(none)
blacklist=() should work then

2024-10-22 09:56 UTC, AkihiroSuda commented on hack/build-integration-canary.sh
> +blacklist=(none)
Thanks

2024-10-22 10:10 UTC, apostasie approved these changes

2024-10-22 15:21 UTC, djdongjin approved these changes
LGTM, thanks

2024-10-22 15:23 UTC, merged