load: import all platforms
containerd/nerdctl pull request #316
Opened 2021-08-17 23:30 UTC by cpuguy83

Currently if you try to import a non-native image the blobs will get
GC'd and unpack fails with with "not found" on the blobs.

Import doesn't really have a way to select which platforms to important,
so I don't think it makes sense to make this optional. After all the tar
could just be modified with the desired platforms.

2021-08-18 04:40 UTC, AkihiroSuda requested changes
This should be gated with `--all-platforms` as in `nerdctl image convert --all-platforms OLD NEW`

In addition to `nerdctl import`, `nerdctl pull` should follow the same semantics, though PR for `nerdctl pull` can be worked out separately
(Obviously nobody wants all the platforms to be pulled by default)

2021-08-18 10:04 UTC, fahedouch commented
Hello,


@cpuguy83  I do not agree with you. the import retrieves the platform to import from the client which is `platforms.DefaultStrict()`

the platform is applied on the client here : https://github.com/containerd/nerdctl/blob/47a4917e40f7923c213d12ec1eee1d9c58e0924a/cmd/nerdctl/load.go#L58

so then the `import` function will get it and initialize the `platformMatcher` with  `platforms.DefaultStrict()` : 
https://github.com/containerd/containerd/blob/fda782a7b941de5438e4fbbd38675bf23b69304b/import.go#L128


I agree with @AkihiroSuda making `all-platforms`  by default is not the it is not the best choice. I think we should keep `platforms.DefaultStrict()` and add `--all-platforms` flag

2021-08-18 14:18 UTC, cpuguy83 commented
Either way is fine.
My main point is the user is supplying the tar to import. It seems strange to not import the whole tar, especially since it seems to be importing them anyway.

2021-08-18 18:05 UTC, cpuguy83 commented
Added the `--all-platforms` flag.

2021-08-18 19:48 UTC, fahedouch commented
LGTM

2021-08-19 05:35 UTC, AkihiroSuda commented on cmd/nerdctl/load.go
> +			Usage: "Imports content for all platforms, false by default",
"false by default" can be removed, as `urfave/cli/v2` appends `(default: false)` automatically

2021-08-19 17:07 UTC, AkihiroSuda approved these changes
Thanks

2021-08-20 02:17 UTC, merged