Fix image output
containerd/nerdctl pull request #357
Opened 2021-09-13 13:03 UTC by fahedouch

avoid creating digest images for each manifest in the index.

fixing https://github.com/containerd/nerdctl/issues/177

2021-09-14 13:38 UTC, ktock requested changes

2021-09-14 13:38 UTC, ktock commented on cmd/nerdctl/load.go
> +	imgs, err := client.Import(ctx, in, containerd.WithAllPlatforms(clicontext.Bool("all-platforms")))
This change makes all non-tagged images loaded by `nerdctl load` get GC-ed immediately.

Example:
```
nerdctl pull busybox:latest
nerdctl save busybox:latest > /tmp/busybox.tar
mkdir /tmp/busybox
tar -C /tmp/busybox -xf /tmp/busybox.tar
jq 'del(.manifests[].annotations)' /tmp/busybox/index.json > /tmp/busybox/index.json.back
mv /tmp/busybox/index.json.back /tmp/busybox/index.json
jq 'del(.[].RepoTags)' /tmp/busybox/manifest.json > /tmp/busybox/manifest.json.back
mv /tmp/busybox/manifest.json.back /tmp/busybox/manifest.json
(...clear containerd cache...)
tar -C /tmp/busybox/ -c . | nerdctl load
(no image loaded here)
```

2021-09-14 13:58 UTC, ktock commented
I believe https://github.com/containerd/containerd/pull/5997 will be needed for solve it. PTAL.

2021-09-21 14:44 UTC, AkihiroSuda commented
> containerd/containerd#5997

Merged

2021-09-21 21:22 UTC, fahedouch commented
thank you @AkihiroSuda , waiting for next containerd release to update the PR.

2021-09-22 15:04 UTC, ktock commented
> waiting for next containerd release to update the PR.

@fahedouch Do we need to wait for the next release? That patch changes only client library so we can work on it with the main branch of containerd.

2021-09-27 06:43 UTC, AkihiroSuda commented
@ktock Would you be interested in carrying this PR?

2021-09-27 08:20 UTC, fahedouch commented
@AkihiroSuda @ktock  
if you allow, I can take care of it

2021-09-27 08:25 UTC, AkihiroSuda commented
Thanks @fahedouch , yes, please

2021-09-27 08:31 UTC, ktock commented
Thanks @fahedouch !

2021-09-27 20:16 UTC, fahedouch commented
@ktock @AkihiroSuda  is it good ?

2021-09-28 00:59 UTC, ktock approved these changes

2021-09-28 14:01 UTC, AkihiroSuda approved these changes
Thanks

2021-09-28 14:01 UTC, merged