Fix pull image process output from stderr to stdout
containerd/nerdctl pull request #3773
Opened 2024-12-17 05:16 UTC by yankay

Fix pull image process output by changing the output stream from stderr to stdout

fix: #3395 
fix: #3772

2024-12-17 06:43 UTC, apostasie approved these changes

2024-12-18 04:36 UTC, AkihiroSuda requested changes
This seems to contaminate the stdout of `nerdctl run` when it incurs pulling an image

2024-12-18 04:43 UTC, apostasie commented
> This seems to contaminate the stdout of `nerdctl run` when it incurs pulling an image

Just tested.
It seems `docker run` does output pull information on stderr, unlike `docker pull`

2024-12-18 04:43 UTC, apostasie commented
@yankay maybe we should have tests for that stuff?

2024-12-19 04:08 UTC, yankay commented
Let me investigate :-)

2024-12-19 10:32 UTC, yankay commented
HI @apostasie @AkihiroSuda 
Would you please help to review it again

2024-12-19 21:50 UTC, apostasie commented on cmd/nerdctl/image/image_pull_linux_test.go
> +			test.Linux,
Is this not working on Windows?

2024-12-19 21:54 UTC, apostasie commented on cmd/nerdctl/image/image_pull_linux_test.go
> +				Expected: func(data test.Data, helpers test.Helpers) *test.Expected {
These are absolutely fine of course ^.

I thought I would mention though that there is also more compact notation when the test commands or conditions are really simple and you do not need access to data or helpers:
```go

Command: test.Command("run", "--rm", testutil.BusyboxImage),
Expected: test.Expects(0, nil, test.DoesNotContains(testutil.BusuboxImage)),
```

2024-12-19 21:55 UTC, apostasie commented on cmd/nerdctl/image/image_pull_linux_test.go
> +				Setup: func(data test.Data, helpers test.Helpers) {
That should be `Cleanup` instead of `Setup` (note: `Cleanup` is called both before `Setup` and after the test completion)

2024-12-19 21:55 UTC, apostasie commented on cmd/nerdctl/image/image_pull_linux_test.go
> +				Setup: func(data test.Data, helpers test.Helpers) {
`Cleanup:`

2024-12-19 21:56 UTC, apostasie reviewed
Thanks @apostasie 
It has changed

2024-12-20 03:18 UTC, yankay commented
> Just a couple of nits on the test.

Thanks @apostasie 
It has changed

2024-12-20 06:01 UTC, AkihiroSuda approved these changes
Thanks

2024-12-20 06:01 UTC, merged